management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  data:
    rest:
      default-page-size: 10
